ASC update article
Azure/AppService pull request #202
Opened 2021-03-12 22:30 UTC by yutanglin16

## Summary

2021-03-12 22:34 UTC, JasonFreeberg commented
## [Preview link](https://antares-blog-staging-pr-202.azurewebsites.net) 
- Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch. 
- The preview site shows any future-dated articles. Don't worry, if you are publishing a future-dated article, it will not show on the production site until the file's specified date.
- The preview link is shareable, but will be deleted when the pull request is merged or closed.
> *This is an automated message.*

2021-03-16 17:12 UTC, JasonFreeberg requested changes

2021-03-16 17:12 UTC, JasonFreeberg commented on _posts/2021-03-17-2020-asc-update-and-faq.md
> +You can still manually renew your certificate up to 60 days before expiration. We are keeping this option open in case you need to renew your certificate earlier, but be aware that the 13-month valid
Missing link for "getting a certificate with "shorter" expiration"

2021-03-16 17:12 UTC, JasonFreeberg commented on _posts/2021-03-17-2020-asc-update-and-faq.md
> +If your certificate is affected by the 13-month validity policy change and have been issued a certificate with a "shorter" expiration, we will not forego the remaining time on the certificate.
Can we try rephrasing this? I don't understand what is meant by "we will not forego the remaining time on the certificate"

2021-03-16 17:12 UTC, JasonFreeberg commented on _posts/2021-03-17-2020-asc-update-and-faq.md
> +There will be a "subscription" policy put in place for your certificate should your renewed certificate have an "shorter" expiration date. Meaning, we will keep a record of the "original" expiration
Last sentence mentions a chart but there isn't one

2021-07-12 15:40 UTC, closed without merging

2023-07-01 01:17 UTC, mster1222 reviewed
work